name: C++ CI test_lib

on: [push, pull_request]
    

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    
    - uses: actions/checkout@v2
    - name: make tests
      run: make test
  
  windows:
    runs-on: windows-latest

    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    
    - uses: actions/checkout@v2
    - name: make tests
      run: make test

    
