on:
  issues:
    types:
      - opened

jobs:
  issue_descriptions:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_BOT }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue view $ISSUE_URL --json body >body.json
          content=$(cat body.json)
          if [[ $content =~ \"body\":\".+\" ]]; then
              echo "All good"
          else
              gh issue comment $ISSUE_URL --body "Please add a description to your issue, before submitting. This was done automatically."
              gh issue close $ISSUE_URL
          fi
